// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Add a node to the network.
Future<String> addNode({required String address}) => RustLib.instance.api
    .crateApiNodeManagementOperationsAddNode(address: address);

/// Remove a node from the network.
Future<String> removeNode({required String address}) => RustLib.instance.api
    .crateApiNodeManagementOperationsRemoveNode(address: address);

/// Check if a node exists in the network.
Future<bool> nodeExists({required String address}) => RustLib.instance.api
    .crateApiNodeManagementOperationsNodeExists(address: address);

/// List all nodes in the network.
Future<List<String>> listNodes() =>
    RustLib.instance.api.crateApiNodeManagementOperationsListNodes();
