// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `NODE_PRIORITIES`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// Set priority for a node.
Future<void> setNodePriority(
        {required String address, required int priority}) =>
    RustLib.instance.api.crateApiNodeManagementPrioritySetNodePriority(
        address: address, priority: priority);

/// Get priority of a node.
Future<int?> getNodePriority({required String address}) => RustLib.instance.api
    .crateApiNodeManagementPriorityGetNodePriority(address: address);
