// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get statistics about the nodes in the network.
Future<(BigInt, List<String>)> getNodeStatistics() =>
    RustLib.instance.api.crateApiNodeManagementStatisticsGetNodeStatistics();

/// Search for nodes matching a given prefix.
Future<List<String>> searchNodes({required String prefix}) =>
    RustLib.instance.api
        .crateApiNodeManagementStatisticsSearchNodes(prefix: prefix);
