// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `NODE_LIST`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// Save the current list of nodes to a file.
Future<void> saveNodesToFile({required String filename}) => RustLib.instance.api
    .crateApiNodeManagementStorageSaveNodesToFile(filename: filename);

/// Load nodes from a file into the network.
Future<void> loadNodesFromFile({required String filename}) =>
    RustLib.instance.api
        .crateApiNodeManagementStorageLoadNodesFromFile(filename: filename);
