// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Validate if the given address is in a valid format.
Future<bool> validateAddress({required String address}) => RustLib.instance.api
    .crateApiNodeManagementValidationValidateAddress(address: address);

/// Check if a node is reachable by attempting a TCP connection.
Future<bool> pingNode({required String address}) => RustLib.instance.api
    .crateApiNodeManagementValidationPingNode(address: address);
